---
- name: create nextcloud db
  docker_container:
    name: "{{ nextcloud.mysql_db_name }}"
    image: "{{ nextcloud.mysql_container_image }}:{{ nextcloud.mysql_container_tag }}"
    state: "{{ nextcloud.state }}"
    restart_policy: "{{ nextcloud.restart_policy }}"
    pull: "{{ nextcloud.pull_policy }}"
    volumes:
      "{{ nextcloud.db_volume }}:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: "{{ nextcloud.mysql_root_pw }}"
      MYSQL_PASSWORD: "{{ nextcloud.mysql_db_pw }}"
      MYSQL_DATABASE: "{{ nextcloud.mysql_db }}"
      MYSQL_USER: "{{ nextcloud.mysql_db_user }}"

- name: create nextcloud smtp
  docker_container:
    name: "{{ nextcloud.containers_prefix }}_smtp"
    image: "{{ nextcloud.smtp_container_image }}:{{ nextcloud.smtp_container_tag }}"
    state: "{{ nextcloud.state }}"
    restart_policy: "{{ nextcloud.restart_policy }}"
    pull: "{{ nextcloud.pull_policy }}"

- name: create nextcloud
  docker_container:
    name: "{{ nextcloud.containers_prefix }}_nextcloud"
    image: "{{ nextcloud.nextcloud_container_image }}:{{ nextcloud.nextcloud_container_tag }}"
    state: "{{ nextcloud.state }}"
    restart_policy: "{{ nextcloud.restart_policy }}"
    links:
      - "{{ nextcloud.mysql_db_name }}"
      - "{{nextcloud.containers_prefix }}_smtp"
    volumes: "{{ nextcloud.remoteip_conf_array }} + ['{{ nextcloud.volume }}:/var/www/html']"
    pull: "{{ nextcloud.pull_policy }}"

- name: create nextcloud nginx
  docker_container:
    name: "{{ nextcloud.containers_prefix }}_web"
    image: "{{ nextcloud.nginx_container_image }}:{{ nextcloud.nginx_container_tag }}"
    state: "{{ nextcloud.state }}"
    restart_policy: "{{ nextcloud.restart_policy }}"
    pull: "{{ nextcloud.pull_policy }}"
    links:
      - "{{nextcloud.containers_prefix }}_nextcloud"
    ports:
      - "{{ nextcloud.nginx_http_port }}:80"
      - "{{ nextcloud.nginx_https_port }}:443"
    volumes:
      - "{{ nextcloud.nextcloud_dir }}/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "{{ nextcloud.nginx_certificate }}"
      - "{{ nextcloud.nginx_certificate_key }}"
