---

- name: Create /var/ansible dir
  file: path=/var/ansible state=directory recurse=yes

- name: Create nextcloud nginx file
  template:
    src: templates/nginx.conf.j2
    dest: "{{ nextcloud_dir }}/nginx.conf"

- name: Create nextcloud remoteip file
  template:
    src: templates/remoteip.conf.j2
    dest: "{{ nextcloud_dir }}/remoteip.conf"
  when: nextcloud.remoteip_configuration is true
