---

- name: Create /var/ansible dir
  file: path=/var/ansible state=directory recurse=yes

- name: Create nextcloud nginx file
  template:
    src: templates/nginx.conf.j2
    dest: /var/ansible/nginx.conf
    name: "{{ nextcloud.db_volume }}"
    state: present
