---
- name: set remote_ip array if remoteip configuration is enabled
  set_fact:
    nextcloud.remoteip_conf_array: "['{{ nextcloud.nextcloud_dir }}/remoteip.conf:/etc/apache2/conf-available/remoteip.conf']"
  when: nextcloud.remoteip_configuration | bool

- include_tasks: files.yml

- include_tasks: volumes.yml

- include_tasks: containers.yml

- include_tasks: cron.yml
  when: nextcloud.cron | bool
